version: '3.3'
services:
  neo4j:
    image: neo4j:3.3
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
    environment:
      NEO4J_AUTH: 'none'
      NEO4J_AUTH_USER: "neo4j"
      NEO4J_AUTH_PASSWORD: "neo4j"
      NEO4J_server_config_strict__validation_enabled: 'false'
      NEO4J_dbms_connector_bolt_listen__address: 0.0.0.0:7687
    volumes:
      - ./volumes/neo4j/data:/data
        - ./volumes/neo4j/conf:/conf

  liferay:
    image: 'liferay/portal:7.4.3.112-ga112'
    environment:
      - LIFERAY_JVM_OPTS=-Xms4g -Xmx4g -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
      - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11311
    ports:
      - 8000:8000
      - 8080:8080
      - 11311:11311
    volumes:
      - './volumes/liferay/data:/opt/liferay/data'
      - './volumes/liferay/deploy:/opt/liferay/deploy'
      - './volumes/liferay/mnt:/mnt/liferay'
    
   